name: clang-format Linter

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Run clang-format"
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: './code'
          extensions: 'hpp,cpp'
          clangFormatVersion: 11
          inplace: True
        
      - name: "Commit clang-format changes"
        uses: EndBug/add-and-commit@v4
        with:
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
